### ISSUE TITLE
creación de vista de paso 2 (step de compromiso) de creación de ordenes de pago

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#11]
al terminar la tarea #7  y en base a los mockups #2 se requiere realizar solo en maquetación el  2 que está allí marcados del modulo de solicitud de autorización de giro

- solo es maquetacion, no necesita trear datos, si necesita datos puede usar datos doomie

***Nota: el enlace de los mockups esta al final de los comentarios***

**Comment by Jeisson005** [comment]
Se agrega el paso 2 de creación de órdenes de pago
![image](https://user-images.githubusercontent.com/24659130/100904587-288c8000-3495-11eb-96aa-993053d6552d.png)
