### ISSUE TITLE
Error 403 release y produccion

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/central_cuentas_cliente#129]
Trabajando en local, no aparece esto, que está apareciendo en ambiente de pruebas y de producción

![image](https://user-images.githubusercontent.com/6588872/125347632-c6e09e00-e320-11eb-8a55-bb7ffea16d9c.png)

**Comment by diagutierrezro** [comment]
Para solucionar este error se habló con @corio27 donde se dió cuenta que este sistema no estaba registrado en el store de WSO2 por lo que se le pasaron los sistemas que usa para realizar el respectivo registro y dar solución al problema
