### ISSUE TITLE
Arreglar Error 500 en Produccion

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/central_cuentas_cliente#133]
![image](https://user-images.githubusercontent.com/6588872/125709649-7fc45a45-d5b4-4caf-a84b-e2582dc58092.png)
![image](https://user-images.githubusercontent.com/6588872/125709631-3ea21dcf-a026-4f7c-88c6-15d03e30b8d1.png)

(Posiblemente también haga parte de / tenga que ver con #124 y/o #130)

**Comment by AlexFBP** [comment]
Logs de configuracion_crud para la petición:

```log
CONTRATISTA,SUPERVISOR,ADMIN_NECESIDADES,ADMIN_PRESUPUESTO,ADMIN_CONTABILIDAD,ESTUDIANTE
[ORM]2021/07/16 16:01:49  -[Queries/default] - [  OK /    db.Query /     6.1ms] - [Select Distinct mo.id AS id, mo.nombre AS nombre, mo.url AS URL, mop.padre AS padre, mo.tipo_opcion
				FROM configuracion.perfil pe, configuracion.perfil_x_menu_opcion pmo,
				configuracion.aplicacion app, configuracion.menu_opcion
				AS mo left join configuracion.menu_opcion_padre
				AS mop ON mo.id = mop.hijo
				WHERE app.id = mo.aplicacion
				AND pe.id = pmo.perfil AND mo.id = pmo.opcion
				AND app.nombre = ('central_cuentas')
				AND pe.nombre IN ('CONTRATISTA','SUPERVISOR','ADMIN_NECESIDADES','ADMIN_PRESUPUESTO','ADMIN_CONTABILIDAD','ESTUDIANTE') AND padre IS NULL ORDER BY mo.id]
Menus padre encontrados:  0
Este es el resultado de la consulta
[]
2021/07/16 16:01:49.207 [1;44m[D][0m [server.go:2807]  |  181.59.201.70|[97;42m 200 [0m|   6.362756ms|   match|[97;44m GET     [0m /v1/menu_opcion_padre/ArbolMenus/CONTRATISTA,SUPERVISOR,ADMIN_NECESIDADES,ADMIN_PRESUPUESTO,ADMIN_CONTABILIDAD,ESTUDIANTE/central_cuentas   r:/v1/menu_opcion_padre/ArbolMenus/:roles/:app
2021/07/16 16:01:49.207 [server.go:3059]  [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)
2021/07/16 16:01:49.207 [1;34m[I][0m [middleware.go:123]  @&configuracion_api@&api.intranetoas.udistrital.edu.co:8086@&/v1/menu_opcion_padre/ArbolMenus/CONTRATISTA,SUPERVISOR,ADMIN_NECESIDADES,ADMIN_PRESUPUESTO,ADMIN_CONTABILIDAD,ESTUDIANTE/central_cuentas@&GET@&2021-07-16 16:01:49.207523952 +0000 UTC m=+26072775.256570807@&181.59.201.70@&Synapse-PT-HttpComponents-NIO@&pruebasoas@&map[RouterPattern:/v1/menu_opcion_padre/ArbolMenus/:roles/:app json:[]]@$ 
```

Se concluye que los menús que están en el ambiente de pruebas no se han pasado al ambiente de producción

**Comment by AlexFBP** [comment]
Si en el ambiente de pruebas en efecto no están construidos los menús, para construirlos se podría tomar como referencia lo realizado en udistrital/arka_cliente#566 
Pero, como de hecho si hay menús construidos, lo más conveniente sería "copiar" (con cuidado) los menús del ambiente de pruebas al de producción

**Comment by diagutierrezro** [comment]
Después de hablar con @blacburn y @corio27 se determina que el error se debe a que el menú no está registrado en producción por lo que se realiza el respectivo registro de este en el api de configuración en producción tomando como guía el menú que se encuentra en pruebas por lo que se realiza lo siguiente:

- Se crea la aplicación en el sistema 
![image](https://user-images.githubusercontent.com/38676533/126212471-6014280d-5e4e-4103-959c-cef821c8113a.png)
- Se crea el rol que usará el sistema
![image](https://user-images.githubusercontent.com/38676533/126212563-e76a5196-754e-424f-988b-2607d8a24dd4.png)
- Se crea el menú ingresando item por item.
![image](https://user-images.githubusercontent.com/38676533/126212661-f023a8dd-dc55-4982-ba35-2e8958f7b18b.png)
Obteniendo el siguiente resultado 
![image](https://user-images.githubusercontent.com/38676533/126212741-7edd11cb-a026-40c4-b3a6-b07f0eb0c613.png)
- Finalmente se configura el rol creado anteriormente para que tenga acceso al menú
- 
![image](https://user-images.githubusercontent.com/38676533/126212844-3e6c1532-dd92-4f49-9639-cc7d662405db.png)


Con esto se puede comprobar que el menú quedo creado de manera correcta y ya no arroja error 500 
![image](https://user-images.githubusercontent.com/38676533/126212983-85981d66-062e-46bf-aaf2-06c621e24bc7.png)

**Comment by AlexFBP** [comment]
Verificado en producción. Cuando sea pertinente, se crearán Issues para la realización de pruebas, tanto en el ambiente de pruebas como en el ambiente de producción; preferentemente de la mano de los mockups (a no ser que hayan actas de aprobación del desarrollo)
