### ISSUE TITLE
Desactivar entradas de menu para todos los roles (ambiente de produccion)

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/central_cuentas_cliente#135]
Continúa #133 

Ya se probó funcional el menú, el objetivo es dejar en el menú de producción solamente los modulos/secciones con visto bueno para produccion

- [x] Desactivar/ocultar entradas

**Comment by diagutierrezro** [comment]
Se desvincula el rol con el menú de central cuentas en producción
![image](https://user-images.githubusercontent.com/38676533/130692110-e4dd8378-b8ca-44da-93c7-e198fe611951.png).
Se evidencia en el cliente que el menú ya no es visible
![image](https://user-images.githubusercontent.com/38676533/130692169-3f943732-70fd-4d63-b07d-9c58db9a6d29.png)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
