### ISSUE TITLE
creación de menú de sistema central de cuentas en cliente de configuración

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#14]

**Comment by Miranda13** [comment]
La ruta para el módulo de aprobaciones es http://localhost:4200/#/pages/aprobaciones

**Comment by Jeisson005** [comment]
Vista para ordenes de pago.

- [ ] Tabla de consulta: http://localhost:4200/#/pages/ordenespago/consultar

- [ ] Creación de órden: http://localhost:4200/#/pages/ordenespago/crear

**Comment by dmarcela09** [comment]
Ruta para Solicitudes de Autorizacion de Giro: http://localhost:4200/#/pages/solicitudesgiros/consultarsolicitudgiro
