### ISSUE TITLE
crear solo vista de paso 3 de creación de ordenes de pago

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#16]

**Comment by Jeisson005** [comment]
Se crea la vista para el paso tres de la creación de órdenes de pago, el resultado es el siguiente:
![image](https://user-images.githubusercontent.com/24659130/101881460-7a529b80-3b62-11eb-86f3-1195aac61c5e.png)

**Comment by Jeisson005** [comment]
Aún no se contempla lo siguiente, ya que se contempla solo vista:

- Validación antes de agregar un registro

- Adición de registro basado en los datos seleccionados

- Conexión general con backend
