### ISSUE TITLE
crear solo vista de paso 4 de creación de ordenes de pago

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#17]

**Comment by Jeisson005** [comment]
Aún no se realiza lo siguiente, ya que se contempla solo vista:

- Funcionalidad del check "Solo información" para deshabilitar campos correspondientes

- Validación antes de agregar un registro a la tabla

- Adición de registro basado en los datos seleccionados (ni registro de prueba)

- Función de eliminación de registro de la tabla

- Suma de valores

- Conexión general con backend

- Uso de store
