### ISSUE TITLE
Creación de mockups web de subsistema central de cuentas

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#2]

**Comment by dmarcela09** [comment]
- [ ] Solicitud Autorización de Giro (Crear una solicitud de Autorización de Giro)
![M](https://user-images.githubusercontent.com/26507343/98388706-17c92580-2021-11eb-8815-1e1f1cbd6d0e.JPG)

- [ ] Ordenes de Pago a Proveedores y Nómina (Crear una solicitud de Orden de Pago)
![M](https://user-images.githubusercontent.com/26507343/98388866-49da8780-2021-11eb-970a-c65c34e6b8be.JPG)

- [ ] Relación de Autorización: Nómina y Funcionarios (Creación de RA y visualización de desagregaciones)
![3](https://user-images.githubusercontent.com/26507343/98389149-accc1e80-2021-11eb-9423-bd6b4f692b67.JPG)

- [ ] Relación de Autorización: Seguridad Social (Creación de RA y visualización de desagregaciones)
![4](https://user-images.githubusercontent.com/26507343/98389175-b5bcf000-2021-11eb-91cf-111eef8dd9d5.JPG)

- [ ] Aprobar Op y Ra (Modificación a las ordenes de pago: Aprobación)
![5](https://user-images.githubusercontent.com/26507343/98389190-b9e90d80-2021-11eb-8f1f-5aa4c9d14407.JPG)

- [ ] Anular Op y Ra (Modificación a las ordenes de pago: Anulación)
![6](https://user-images.githubusercontent.com/26507343/98389201-bd7c9480-2021-11eb-8cd3-5da3919f960b.JPG)

- [ ] Borrar Op y Ra (Modificación a las ordenes de pago: Eliminación)
![7](https://user-images.githubusercontent.com/26507343/98389213-c1101b80-2021-11eb-9250-ff6951d9d8a3.JPG)

- [ ] Solicitud de Devolución (Crear tipos de solicitud de devolución)
![8](https://user-images.githubusercontent.com/26507343/98389232-c4a3a280-2021-11eb-954a-50d4629c34f4.JPG)

- [ ] Devolución Tributaria (Crear una solicitud de devolución tributaria)
![9](https://user-images.githubusercontent.com/26507343/98389241-c79e9300-2021-11eb-9251-dd117610c308.JPG)

**Comment by dmarcela09** [comment]
Comparto el [enlace](https://drive.google.com/file/d/1-MTBk3UVCgHnCx-DuarrJXoXyEjkvsFn/view?usp=sharing) de los mockups: https://drive.google.com/file/d/1-MTBk3UVCgHnCx-DuarrJXoXyEjkvsFn/view?usp=sharing
