### ISSUE TITLE
realizar ajustes visuales propuestos por el usuario a ordenes de pago

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#26]
en base a los ajustes dados por el usuario solo requiere de la tabla de ordenes de pago quitar las columnas de mes y quincena

**Comment by Jeisson005** [comment]
Se eliminan las columnas mes y quincena de la tabla, el resultado es el siguiente:
![image](https://user-images.githubusercontent.com/24659130/101882716-40829480-3b64-11eb-8dce-889a9f15bccb.png)
