### ISSUE TITLE
adiciones y ajustes a ordenes de pago

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#39]
se requieren realizar los siguientes ajustes y adiciones

- [x] en el paso 4 cambiar los siguientes labels
  - `descuento` por `% de descuento `
  - `valor (con descuento)` por `valor de descuento`

- [x] se debe de realizar el calculo del descuento en el campo de `valor de descuento` , el valor se calculo usando la base de retención y a esa base se le saca el porcentaje de descuento, este resultado se debe de calculas automáticamente si el usuario cambia la base de retención

**Comment by Jeisson005** [comment]
Se realiza ajuste de nombre y cálculo automático
![image](https://user-images.githubusercontent.com/24659130/102853351-2a8b9400-43ee-11eb-9cf2-cb05f0a83c0f.png)

**Comment by Jeisson005** [comment]
Para el cálculo completo aún falta traer el porcentaje de descuento y los demás datos correspondientes a la retención.
Por lo que se colocan valores por defecto por el momento
