### ISSUE TITLE
crear vista de datos de solicitante para solicitud de devolucion de otros conceptos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#60]
en base a los mockups del issue #2 se requiere realizar la maquetacion de  la sección de ingreso de datos del solicitante para la solicitud de devolución

***nota se recomienda que sea un componente que se comparta con la tarea #61 , para ello puede mandar parámetros por la ruta pasa saber si se esta usando para devolución por impuestos o por otros conceptos***

**Comment by Jeisson005** [comment]
Se crea paso dos (datos de solicitante) para la vista de creación de solicitudes de devolución
![image](https://user-images.githubusercontent.com/24659130/103082422-0ecbed80-45a8-11eb-92b1-c234addbbafd.png)

**Comment by Jeisson005** [comment]
La vista es el mismo componente que en el issue #61 
Ésto ya que los mockups son idénticos.
**Se planea compartir la información entre los componentes (incluyendo la opción seleccionada en el paso uno con los otros pasos) haciendo uso de redux**
