### ISSUE TITLE
crear vista de datos de solicitante para solicitud de devolucion de impuestos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#61]
en base a los mockups del issue #2 se requiere realizar la maquetacion de  la sección de ingreso de datos del solicitante para la solicitud de devolución para otros conceptos

***nota se recomienda que sea un componente que se comparta con la tarea #60 , para ello puede mandar parámetros por la ruta pasa saber si se esta usando para devolución por impuestos o por otros conceptos***

**Comment by Jeisson005** [comment]
Se crea paso dos (datos de solicitante) para la vista de creación de solicitudes de devolución
![image](https://user-images.githubusercontent.com/24659130/103082443-17242880-45a8-11eb-93d2-c4ed196e7ec9.png)

**Comment by Jeisson005** [comment]
La vista es el mismo componente que en el issue #60 
Ésto ya que los mockups son idénticos.
**Se planea compartir la información entre los componentes (incluyendo la opción seleccionada en el paso uno con los otros pasos) haciendo uso de redux**
