### ISSUE TITLE
crear vista de anexos para solicitud de devolucion de otros conceptos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#62]
en base a los mockups del issue #2 se requiere realizar la maquetacion de  la sección de ingreso de anexos para la solicitud de devolución

para ello, también es necesario que en la interfaz funcione el cargar archivos, se sabe que no se almacenaran en ningún lado pero la funcionalidad de permitir subir archivos ya existe, se puede basar en el modulo de solicitud de giro que ya implementa esto, en caso que se requiera se puede llamar ese componente a este modulo, pero para hacerlo ese componente debe de pasarse a estar en el `shated`

***nota se recomienda que sea un componente que se comparta para otra tarea futura relacionada con la solicitud de devolución de otros conceptos, para ello puede mandar parámetros por la ruta pasa saber si se esta usando para devolución por impuestos o por otros conceptos***

**Comment by Jeisson005** [comment]
Se crea el paso tres en la vista de creación de solicitudes de devolución. Cargue de anexos
![image](https://user-images.githubusercontent.com/24659130/103085660-59e9fe80-45b0-11eb-8c41-6f1608e47212.png)

**Comment by Jeisson005** [comment]
Se planea utilizar redux para las variaciones en las vistas.
**Se planea compartir la información entre los componentes (incluyendo la opción seleccionada en el paso uno con los otros pasos) haciendo uso de redux**
