### ISSUE TITLE
realizar tabla y paso 1 de ordenes de pago

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#7]
en base a los mockups #2 se requiere realizar solo en maquetación la tabla y el paso 1 que están allí marcados del modulo de orden de pago.

se debe de tener en cuenta 

- lazy loading, por lo tanto se debe de crear un modulo para esta seccion de autorizacion de giro y dentro de este se encontraran los respectivos componentes. 

- todo debe ir en componentes, se debe de tener en cuenta el concepto de atomicidad 

***Nota: el en lace de los mockups esta al final de los comentarios***

- [x] Tabla de órdenes de pago

- [x] Paso uno de órdenes de pago

**Comment by Jeisson005** [comment]
Se crea nueva vista con tabla de órdenes de pago como se visualiza a continuación.
La nueva ruta es la siguiente: http://localhost:4200/#/pages/consultaordenespago
![image](https://user-images.githubusercontent.com/24659130/99859954-aaa8aa80-2b5f-11eb-9ca6-fbcc4c849d49.png)

**Comment by Jeisson005** [comment]
Se crea nueva vista con tabla de órdenes de pago como se visualiza a continuación.
La nueva ruta es la siguiente: http://localhost:4200/#/pages/ordenespago/crear

![image](https://user-images.githubusercontent.com/24659130/100904028-8ff60000-3494-11eb-84f2-f71dcd23f5cb.png)
