### ISSUE TITLE
crear vista de anexos para solicitud de devolucion de impuestos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#83]
en continuacion al issue #62 se requiere realizar una seccion de anexos de solicitud de devolucion en este caso para  **impuestos**, esto usando como base los mockups #2 

para este issue se pedira. 

- [x] drag and drop de archivos
- [x] confirmar que los archivos sean subidos

- [x] una mejora estetica

**Comment by Jeisson005** [comment]
Se crea la vista solicitada, el resultado es el siguiente:
![image](https://user-images.githubusercontent.com/24659130/103393614-87bfcd80-4af1-11eb-94fe-f872137b5f21.png)
![image](https://user-images.githubusercontent.com/24659130/103393618-8d1d1800-4af1-11eb-88b2-371cf8acfe43.png)

**Comment by Jeisson005** [comment]
Se realiza lo siguiente:

- Componente compartido para cargue de archivos mediante "arrastrar y soltar" (componente _file-upload_)
- "Confirmación" de cargue de archivos almacenandolos en la tabla (allí se visualiza el nombre, pero también se encuentra el objeto _File_)
- Una mejora estética con base en los mockups del issue #2: Se agregan estilos a las pestañas de anexos e impuestos, y el cargue de archivos se visualiza igual que en el mockup
- El componente para el gargue de anexos e impuestos se reutiliza, por lo que cambia dependiendo el tipo de devolución elegidos
