### ISSUE TITLE
crear vista de impuestos para solicitud de devolucion de impuestos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#85]
con base a los mockups #2 se requiere realizar la sección de impuestos para la solicitud de devolución de impuestos

**Comment by Jeisson005** [comment]
Se crea la vista solicitada, el resultado es el siguiente:
![image](https://user-images.githubusercontent.com/24659130/103393419-9063d400-4af0-11eb-9ded-2881cde74ff9.png)
