### ISSUE TITLE
crear vista de guardar para solicitud de devolución de otros conceptos e impuestos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#91]
con base en los mockuos #2 se requiere crear la vista de resumen que tiene el nombre en el step de guardar, para el modulo de solicitud de devolución

**Comment by Jeisson005** [comment]
Se crea la vista solicitada, el resultado es el siguiente:
![image](https://user-images.githubusercontent.com/24659130/103834493-8e01fc80-5051-11eb-8f5e-25147fe1f19e.png)
![image](https://user-images.githubusercontent.com/24659130/103834509-99552800-5051-11eb-9e03-09fe707dc7b2.png)
