### ISSUE TITLE
consumir vigencias del cliente de presupuesto con base al area funcional seleccionada

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/central_cuentas_cliente#96]
para la sección de ordenes de pago es necesario pedir la vigencia y que esta sea seleccionada por ende se requiere realizar la solicitud y pasarla por el store usando redux

la petición sugerida de la siguiente

```
https://autenticacion.portaloas.udistrital.edu.co/apioas/plan_cuentas_mongo_crud/v1/vigencia/vigencias_total
```
para que la tarea se culmine exitosamente se requiere:

- [x] usar redux para almacenar la vigencias, las cuales se almacenaran en el store del shared

- [x] se debe de realizar proceso de verificación para saber si ya previamente ya se habían consultado las vigencias ya que esto agilizara el cliente para no tener que realizar la petición mas de una vez

- [x] el select de "tipo orden de pago" debe de cambiarse a un input desactivado, 

- [x] el endpoint trae las vigencias de todas las areas de funcionamiento, por ende solo mostrar las vigencias segun el area de funcionamiento seleccionada (se recomienda usar la funcion filter de los array methods). 

- [x] la vigencia futura se debe ser omitida para estos casos ya que no se usara

- [x] el campo mencionado en un item anterior debe de cambiar segun la vigencia seleccionada.
   - cuando se seleccione la vigencia actual el campo debe de decir `Vigencia Actual`
   - cuando se seleccione la vigencia inmediatamente anterior a la actual el campo debe de decir `Reserva`
   -  cuando se seleccione la vigencia es de 2 o mas años anterior a la actual el campo debe de decir `Pasivo Exigible`
   - se recomienda usar pipes

**Comment by Jeisson005** [comment]
Se realiza el consumo de las vigencias.
El resultado es el siguiente:
![image](https://user-images.githubusercontent.com/24659130/103825762-7c195d00-5043-11eb-83be-5e5ce19466a8.png)
![image](https://user-images.githubusercontent.com/24659130/103825796-86d3f200-5043-11eb-9f5f-b61dc1dbcbf8.png)
Se realizó lo siguiente:

- Se implementa _redux_ en el _shared_ para guardar las vigencias
- Se realiza la verificación para generar la solicitud solo una vez, esto en el efecto _redux_
- El _select_ de "tipo orden de pago" se cambia a un _input_ desactivado
- Mediante la función _filter_, se filtran las vigencias según el área seleccionada, el filtro se realiza en el archivo _typescript_ del componente
- Se filtran las vigencias futuras haciendo uso de un selector, se colocó en el selector con el fin almacenar todas las vigencias en el _store_ incluyendo las futuras en caso de que se requieran usar en otro módulo o componente
- Se crea un _pipe_ en el módulo para la visualización del tipo de orden de pago
